import os.path

def use_module(bld):

    version = '1.0.0'

    depends_on = []

    sources = bld.path.ant_glob(['src/**/*.xc', 'src/**/*.c', 'src/**/*.S'])
    includes = ['api']
    optional_headers = []

    bld.env.MODULE_XCC_FLAGS = bld.env.XCC_FLAGS + ['-Os']

    bld.module(
        source=sources,
        includes=includes,
        optional_headers=optional_headers,
        depends_on=depends_on,
        version=version)
