TARGET = SMART-MIC-4-TILE-1V0
APP_NAME =
USED_MODULES = lib_random

XCC_FLAGS = -O2 -g -Wunused -fxscope
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
