TARGET = STARTKIT
APP_NAME =
USED_MODULES = lib_random

XCC_FLAGS = -Os -g

#XCC_FLAGS += -save-temps -v

XCORE_ARM_PROJECT = 0
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
