TARGET = STARTKIT
APP_NAME =
USED_MODULES = lib_random

XCC_FLAGS = -Os -g -fcmdline-buffer-bytes=100
#XCC_FLAGS += -save-temps -v


XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
