TARGET = SLICEKIT-L16
APP_NAME =
USED_MODULES = lib_random

XCC_FLAGS = -Os -g
#XCC_FLAGS += -save-temps -v

# We will be testing the deprecated interface...
RANDOM_ENABLE_HW_SEED=1

VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
